[package]
name = "icons"
version = "0.1.0"
edition = "2021"

[lib]
path="icons.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
